# Generated by Django 4.2.3 on 2023-08-01 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="api",
            old_name="users",
            new_name="mapped_users",
        ),
    ]
